apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  labels:
    type: front-end
spec:
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        type: front-end
    spec:
      containers:
      - name: elasticsearch
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      type: front-end
