apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    type: front-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 - key: size
                   operator: In
                   values:
                     - XL
                     - L
  replicas: 3
  selector:
    matchLabels:
      type: front-end
