apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp
    image: httpd
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: log-volume

  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: pvc-webapp