apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    type: app
spec:
    containers:
      - name: webapp
        image: httpd
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs
            name: app-volume
    volumes:
       - name: app-volume
         hostPath:
          path: /tmp/htdocs
          type: Directory

