apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: website
spec:
  containers:
   - name: postgres
     image: postgres:9.4
     ports:
      - containerPort: 5432
     env:
       - name: POSTGRES_HOST_AUTH_METHOD
         valueFrom:
           configMapKeyRef:
             name: postgres-config-map
             key: POSTGRES_HOST_AUTH_METHOD

