apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: voting-website
spec:
  replicas: 1

  template:
    metadata:
      name: postgres-pod
      labels:
        app: voting-website
        name: postgres-pod
    spec:
      containers:
       - name: postgres
         image: postgres:9.4
         ports:
           - containerPort: 5432

  selector:
    matchLabels:
      app: voting-website
      name: postgres-pod
