apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: voting-website
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-website
    name: result-app-pod